branch-defaults:
  master:
    environment: docker-sails-app2-dev
    group_suffix: null
global:
  application_name: docker-sails-app2
  default_ec2_keyname: aws-eb
  default_platform: Docker 1.9.1
  default_region: us-west-1
  profile: eb-cli
  sc: git
